/**
 * Form 16, Part B — the annual salary and tax certificate an employer gives
 * each employee by 15 June.
 *
 * Part A (the TDS deposited, quarter by quarter) is generated by TRACES from
 * the 24Q returns and downloaded from the department; PEPL cannot make it.
 * Part B is ours: what was paid in the year, what was exempt, the Chapter
 * VI-A deductions the employer allowed, the tax computed on it, and the tax
 * actually deducted. Every figure comes from locked runs and the verified
 * declaration — the same rows the payslips and the 24Q were built from — so
 * the three documents agree by construction.
 */
import type { PoolClient } from 'pg'
import { allowableDeductions, type Allowance } from './chapter-via.ts'
import { getDeclaration } from './declarations.ts'
import { taxOnIncome, type TaxRules, type TaxSlab } from './tds.ts'
import { PdfPage, renderPdf, PAGE_WIDTH } from '../pdf/document.ts'
import { rupees } from './payslip-pdf.ts'

export class Form16Error extends Error {
  readonly code: string
  constructor(code: string, message: string) {
    super(message)
    this.code = code
    this.name = 'Form16Error'
  }
}

export interface Form16 {
  fiscalYear: string
  employee: { id: string; number: string; name: string; pan: string | null; designation: string | null }
  employer: { name: string; tan: string | null; pan: string | null }
  regime: 'old' | 'new'
  months: number
  /** Paise. */
  grossSalaryPaise: number
  exemptAllowancesPaise: number          // s.10: HRA exemption, gratuity, leave encashment at exit
  standardDeductionPaise: number
  professionalTaxPaise: number
  incomeFromSalaryPaise: number
  chapterVia: Allowance
  taxableIncomePaise: number
  taxOnIncomePaise: number
  rebate87aPaise: number
  cessPaise: number
  surchargePaise: number
  totalTaxPaise: number
  tdsDeductedPaise: number
  /** +ve: still owed; −ve: refund due via the return. */
  balancePaise: number
  components: { code: string; annualPaise: number }[]
  notes: string[]
}

const fyBounds = (fy: string): { from: string; to: string } => {
  const y = Number(fy.slice(0, 4))
  return { from: `${y}-04-01`, to: `${y + 1}-03-31` }
}

export async function buildForm16(
  tx: PoolClient,
  args: { employeeId: string; fiscalYear: string; slabs: Partial<Record<'old' | 'new', TaxSlab[]>>; rules: Partial<Record<'old' | 'new', TaxRules>>; tan?: string | null; employerPan?: string | null },
): Promise<Form16> {
  if (!/^\d{4}-\d{2}$/.test(args.fiscalYear)) throw new Form16Error('VALIDATION_FAILED', 'fiscalYear must look like 2026-27')
  const { from, to } = fyBounds(args.fiscalYear)

  const { rows: emp } = await tx.query<{ employee_number: string; name: string; pan: string | null; designation: string | null; company: string }>(
    `SELECT e.employee_number, concat_ws(' ', e.first_name, e.last_name) AS name, s.pan, a.designation, t.display_name AS company
       FROM employees e
       JOIN tenants t ON t.id = e.tenant_id
       LEFT JOIN employee_statutory_ids s ON (s.tenant_id, s.employee_id) = (e.tenant_id, e.id)
       LEFT JOIN LATERAL (SELECT designation FROM employee_assignments x WHERE (x.tenant_id, x.employee_id) = (e.tenant_id, e.id)
                           AND x.superseded_at IS NULL AND x.effective_from <= $2::date ORDER BY x.effective_from DESC LIMIT 1) a ON true
      WHERE e.id = $1`, [args.employeeId, to])
  if (!emp[0]) throw new Form16Error('NOT_FOUND', 'no such employee')

  // Everything paid in the year, from locked, non-superseded runs.
  const { rows: lines } = await tx.query<{ code: string; type: string; total: string; exempt: boolean; months: string }>(
    `SELECT l.component_code AS code, l.component_type AS type, sum(l.amount_paise)::text AS total,
            bool_or(coalesce((l.calc_note ->> 'taxExempt')::boolean, false)) AS exempt,
            count(DISTINCT l.run_id)::text AS months
       FROM payroll_lines l
       JOIN payroll_runs r ON (r.tenant_id, r.id) = (l.tenant_id, l.run_id)
       JOIN payroll_periods pp ON (pp.tenant_id, pp.id) = (r.tenant_id, r.period_id)
      WHERE l.employee_id = $1 AND r.status = 'locked' AND pp.period_start BETWEEN $2::date AND $3::date
        AND NOT EXISTS (SELECT 1 FROM payroll_runs n WHERE n.tenant_id = r.tenant_id AND n.supersedes_run_id = r.id AND n.status = 'locked')
      GROUP BY l.component_code, l.component_type`, [args.employeeId, from, to])
  if (!lines.length) throw new Form16Error('NO_PAY_IN_YEAR', `nothing was paid to this employee in ${args.fiscalYear} from a locked run`)

  const n = (c: string): number => Number(lines.find((l) => l.code === c)?.total ?? 0)
  const earnings = lines.filter((l) => l.type === 'earning')
  const gross = earnings.reduce((s, l) => s + Number(l.total), 0) - n('LOP')
  const exemptComponents = earnings.filter((l) => l.exempt).reduce((s, l) => s + Number(l.total), 0)
  const months = Math.max(...lines.map((l) => Number(l.months)))

  const declaration = await getDeclaration(tx, args.employeeId, args.fiscalYear)
  const regime: 'old' | 'new' = declaration?.regime ?? 'new'
  const basic = n('BASIC') + n('DA'), hra = n('HRA')
  const chapterVia = declaration?.status === 'verified'
    ? allowableDeductions(declaration.declared, { basicAnnualPaise: basic, hraAnnualPaise: hra }, args.fiscalYear, regime)
    : { regime, totalPaise: 0, hraExemptionPaise: 0, lines: [], notes: [declaration ? `declaration ${declaration.status}, not verified: no deductions allowed` : 'no declaration on file'] }

  const rules = args.rules[regime]
  const slabs = args.slabs[regime] ?? []
  if (!rules || !slabs.length) throw new Form16Error('NO_TAX_RULES', `no tax slabs configured for the ${regime} regime in ${args.fiscalYear}`)

  const exempt = exemptComponents + chapterVia.hraExemptionPaise
  const standardDeduction = Number(rules.standard_deduction_paise)
  const pt = n('PT')
  const incomeFromSalary = Math.max(0, gross - exempt - standardDeduction - pt)
  const viaOnly = chapterVia.totalPaise - chapterVia.hraExemptionPaise
  const taxable = Math.max(0, incomeFromSalary - viaOnly)
  let tax = taxOnIncome(taxable, slabs)
  let rebate = 0
  if (Number(rules.rebate_limit_paise) > 0 && taxable <= Number(rules.rebate_limit_paise)) { rebate = Math.min(tax, Number(rules.rebate_max_paise)); tax -= rebate }
  let surchargeRate = 0
  for (const b of rules.surcharge_bands ?? []) if (taxable > b.above_paise) surchargeRate = b.rate
  const surcharge = Math.round(tax * surchargeRate)
  const cess = Math.round((tax + surcharge) * Number(rules.cess_rate))
  const total = Math.round((tax + surcharge + cess) / 100) * 100
  const tds = n('TDS')

  return {
    fiscalYear: args.fiscalYear,
    employee: { id: args.employeeId, number: emp[0].employee_number, name: emp[0].name, pan: emp[0].pan, designation: emp[0].designation },
    employer: { name: emp[0].company, tan: args.tan ?? null, pan: args.employerPan ?? null },
    regime, months,
    grossSalaryPaise: gross, exemptAllowancesPaise: exempt, standardDeductionPaise: standardDeduction, professionalTaxPaise: pt,
    incomeFromSalaryPaise: incomeFromSalary, chapterVia, taxableIncomePaise: taxable,
    taxOnIncomePaise: Math.round(tax + rebate), rebate87aPaise: Math.round(rebate), surchargePaise: surcharge, cessPaise: cess,
    totalTaxPaise: total, tdsDeductedPaise: tds, balancePaise: total - tds,
    components: earnings.map((l) => ({ code: l.code, annualPaise: Number(l.total) })).sort((a, b) => b.annualPaise - a.annualPaise),
    notes: [
      ...chapterVia.notes,
      'Part A (tax deposited, quarter by quarter) is issued from TRACES against the 24Q returns; this is Part B.',
      ...(!emp[0].pan ? ['No PAN on record: the department deducts at 20% and this certificate cannot be matched to a return.'] : []),
      ...(months < 12 ? [`${months} month(s) paid in the year; income from other employers is not included.`] : []),
    ],
  }
}

/** A one-page Part B. */
export function form16Pdf(f: Form16): Buffer {
  const page = new PdfPage()
  const left = 48, right = PAGE_WIDTH - 48
  let y = 800
  const row = (label: string, paise: number | null, opts: { bold?: boolean; indent?: number } = {}): void => {
    page.text(label, left + (opts.indent ?? 0), y, { size: 10, font: opts.bold ? 'bold' : 'regular' })
    if (paise !== null) page.textRight(rupees(paise), right, y, { size: 10, font: opts.bold ? 'bold' : 'regular' })
    y -= 16
  }
  page.text('FORM NO. 16 — PART B', left, y, { size: 14, font: 'bold' }); y -= 18
  page.text(`Details of salary paid and tax deducted · Financial year ${f.fiscalYear} (${f.regime} regime)`, left, y, { size: 10, grey: 0.3 }); y -= 22
  page.text(`Employer: ${f.employer.name}${f.employer.tan ? ` · TAN ${f.employer.tan}` : ''}`, left, y, { size: 10 }); y -= 14
  page.text(`Employee: ${f.employee.name} (${f.employee.number})${f.employee.designation ? ` · ${f.employee.designation}` : ''}${f.employee.pan ? ` · PAN ${f.employee.pan}` : ' · PAN not on record'}`, left, y, { size: 10 }); y -= 22
  page.line(left, y, right, y); y -= 16

  row('1. Gross salary', f.grossSalaryPaise, { bold: true })
  for (const c of f.components) row(c.code, c.annualPaise, { indent: 14 })
  row('2. Less: allowances exempt under section 10', f.exemptAllowancesPaise)
  if (f.chapterVia.hraExemptionPaise) row('House rent allowance u/s 10(13A)', f.chapterVia.hraExemptionPaise, { indent: 14 })
  row('3. Less: standard deduction u/s 16(ia)', f.standardDeductionPaise)
  row('4. Less: tax on employment u/s 16(iii)', f.professionalTaxPaise)
  row('5. Income chargeable under the head Salaries', f.incomeFromSalaryPaise, { bold: true })
  row('6. Deductions under Chapter VI-A', f.chapterVia.totalPaise - f.chapterVia.hraExemptionPaise)
  for (const l of f.chapterVia.lines.filter((l) => !l.section.startsWith('HRA'))) row(`${l.section}`, l.allowedPaise, { indent: 14 })
  row('7. Total taxable income', f.taxableIncomePaise, { bold: true })
  row('8. Tax on total income', f.taxOnIncomePaise)
  if (f.rebate87aPaise) row('9. Less: rebate u/s 87A', f.rebate87aPaise)
  if (f.surchargePaise) row('10. Surcharge', f.surchargePaise)
  row('11. Health and education cess', f.cessPaise)
  row('12. Tax payable', f.totalTaxPaise, { bold: true })
  row('13. Tax deducted at source', f.tdsDeductedPaise)
  row(f.balancePaise >= 0 ? '14. Balance tax payable' : '14. Refund due', Math.abs(f.balancePaise), { bold: true })
  y -= 6
  page.line(left, y, right, y); y -= 14
  for (const note of f.notes) { page.text(note, left, y, { size: 8, grey: 0.35 }); y -= 11 }
  page.text('Generated by PEPL from locked payroll runs. Verification by the person responsible for deduction is required before issue.', left, 40, { size: 7, grey: 0.5 })
  return renderPdf(page, `Form 16 Part B ${f.fiscalYear} ${f.employee.number}`)
}
