import { SecurityCard } from './security/Mfa'
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError, dateLabel, fullName, dateTimeLabel } from './api'
import { domainApi } from './domainApi'
import { removeCurrentPushSubscription } from './push'
import { Button, Card, PageHeader, PasswordInput } from './ui'
import type { Employee, Workspace } from './types'

export function PasswordRecovery({ token }: { token?: string | null }) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [sent,setSent]=useState(false)
  const reset=token!==undefined
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{
    if(reset){await domainApi('/auth/reset-password',{token:token??'',newPassword:values.newPassword});location.assign('/')}
    else {await domainApi('/auth/forgot-password',{email:values.email});setSent(true)}
  }catch(caught){if(caught instanceof ApiError && caught.code==='RESET_TOKEN_INVALID')setError('This reset link is invalid or has expired. Request a new link.');else if(caught instanceof ApiError && caught.status===429){const wait=String(caught.details?.retryAfter??'');setError(`Too many requests. ${/^\d+$/.test(wait)?`Wait ${wait} seconds`:wait?`Try again after ${wait}`:'Please wait before trying again'}.`)}else setError(caught instanceof Error?caught.message:'Unable to continue')}finally{setBusy(false)}}
  return <div className="recovery-page"><Card><span className="eyebrow">PEPL account</span><h1>{reset?'Choose a new password':'Forgot your password?'}</h1>{sent?<p role="status">If that address has an account, a link is on its way.</p>:<form className="lifecycle-form" onSubmit={submit}>{reset?<><p>Use at least 10 characters. Resetting your password signs out every session.</p><label>New password<PasswordInput name="newPassword" aria-label="New password" minLength={10} autoComplete="new-password" required/></label></>:<label>Work email<input name="email" type="email" autoComplete="username" required/></label>}<Button disabled={busy}>{busy?'Please wait…':reset?'Reset password':'Send reset link'}</Button></form>}{error&&<p role="alert" className="form-error">{error}</p>}<a href={reset?'/#/forgot-password':'/#/dashboard'}>{reset?'Request a new reset link':'Back to sign in'}</a></Card></div>
}

type Session={id:string;issued_at:string;last_seen_at:string;expires_at:string;ip:string|null;user_agent:string|null;current:boolean}
export function AccountSettings({data}:{data:Workspace}){
  const [sessions,setSessions]=useState<Session[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false)
  const [directory,setDirectory]=useState<Employee[]>([]);const [userId,setUserId]=useState('');const [link,setLink]=useState<{link:string;expiresAt:string}|null>(null)
  const load=useCallback(async()=>{setSessions((await domainApi<{sessions:Session[]}>('/auth/sessions')).sessions)},[])
  useEffect(()=>{void load().catch(caught=>setError(caught.message));if(data.permissions.includes('roles.write'))void domainApi<{employees:Employee[]}>('/employees?limit=200').then(result=>setDirectory(result.employees.filter(employee=>employee.user_id))).catch(caught=>setError(caught.message))},[load,data.permissions])
  const change=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{const result=await domainApi<{sessionsRevoked:number}>('/auth/change-password',values);setNotice(`Password changed. ${result.sessionsRevoked} other sessions signed out. This session remains active.`);form.reset();await load()}catch(caught){setError(caught instanceof ApiError&&caught.code==='INVALID_CREDENTIALS'?'The current password is incorrect.':caught instanceof Error?caught.message:'Unable to change password')}finally{setBusy(false)}}
  const revoke=async(session:Session)=>{setBusy(true);setError('');try{if(session.current)await removeCurrentPushSubscription().catch(()=>undefined);await domainApi(`/auth/sessions/${session.id}`,undefined,'DELETE');if(session.current){location.assign('/');return}await load();setNotice('Device signed out.')}catch(caught){setError(caught instanceof Error?caught.message:'Unable to sign out device')}finally{setBusy(false)}}
  const issue=async()=>{setBusy(true);setError('');setLink(null);try{setLink(await domainApi(`/users/${userId}/password-reset-link`,{}))}catch(caught){setError(caught instanceof Error?caught.message:'Unable to issue recovery link')}finally{setBusy(false)}}
  return <><PageHeader title="Account settings" description="Your password, your second factor, and the devices signed in to your account." eyebrow="Personal security"/><SecurityCard canReset={data.permissions.includes('settings.write')} users={directory.filter(e=>e.user_id).map(e=>({id:e.user_id!,name:`${fullName(e)} · ${e.employee_number}`}))}/><div className="two-column"><Card title="Change password" subtitle="At least 10 characters. Your other sessions will be signed out."><form className="lifecycle-form" onSubmit={change}><label>Current password<PasswordInput required name="currentPassword" aria-label="Current password" autoComplete="current-password"/></label><label>New password<PasswordInput required name="newPassword" aria-label="New password" minLength={10} autoComplete="new-password"/></label><Button disabled={busy}>Change password</Button></form></Card><Card title="Signed-in devices" subtitle="Current device appears first"><div className="session-list">{sessions.map(session=><article key={session.id}><strong>{session.current?'This device':'Other device'}</strong><p>{session.user_agent??'Unknown browser'}</p><small>{session.ip??'Unknown IP'} · Last seen {dateLabel(session.last_seen_at)} · Expires {dateLabel(session.expires_at)}</small><Button variant="secondary" disabled={busy} onClick={()=>void revoke(session)}>Sign out {session.current?'this device':'device'}</Button></article>)}</div></Card></div>{data.permissions.includes('roles.write')&&<Card title="Administrator account recovery" subtitle="Issue a link when a colleague cannot receive recovery email"><div className="bank-file-controls"><label>Colleague<select value={userId} onChange={event=>{setUserId(event.target.value);setLink(null)}}><option value="">Choose colleague</option>{directory.map(employee=><option key={employee.id} value={employee.user_id??''}>{fullName(employee)} · {employee.employee_number}</option>)}</select></label><Button disabled={busy||!userId} onClick={()=>void issue()}>Issue recovery link</Button></div>{link&&<div className="declaration-alert"><div><strong>This link grants access as the selected person.</strong><p>Share it only with that person. Displayed once; expires {dateTimeLabel(link.expiresAt)}.</p><input readOnly value={link.link} aria-label="Recovery link"/><Button variant="secondary" onClick={()=>{void navigator.clipboard.writeText(link.link).then(()=>setNotice('Recovery link copied.')).catch(()=>setError('Unable to copy. Select and copy the link manually.'))}}>Copy link</Button><Button variant="ghost" onClick={()=>setLink(null)}>Dismiss link</Button></div></div>}</Card>}{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}</>
}
