import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError, dateLabel, money, pretty } from './api'
import { domainApi, downloadFile } from './domainApi'
import type { Employee, Workspace } from './types'
import { Button, Card, Modal } from './ui'

type Ids = { uan: string | null; pan: string | null; esi_number: string | null; pf_member_id: string | null }
export function StatutoryIds({ id, canWrite }: { id: string; canWrite: boolean }) {
  const [ids, setIds] = useState<Ids | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setIds((await domainApi<{ statutoryIds: Ids | null }>(`/employees/${id}/statutory-ids`)).statutoryIds) }, [id])
  useEffect(() => { void load().catch(caught => setError(caught.message)) }, [load])
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const body = Object.fromEntries([...new FormData(event.currentTarget)].filter(([,value]) => String(value).trim()))
    setBusy(true); setError('')
    try { await domainApi(`/employees/${id}/statutory-ids`, body, 'PATCH'); await load(); setNotice('Statutory identifiers saved.') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save identifiers') } finally { setBusy(false) }
  }
  return <Card title="Statutory identifiers" subtitle="Private payroll details. Omitted fields are kept unchanged.">
    <div className="identifier-warnings">{!ids?.uan && <span className="status-pill status-rejected">Missing UAN — excluded from ECR</span>}{!ids?.pan && <span className="status-pill status-rejected">Missing PAN — excluded from 24Q</span>}</div>
    <form onSubmit={save} key={JSON.stringify(ids)} className="lifecycle-form">{[{name:'uan',label:'UAN',value:ids?.uan,pattern:'[0-9]{12}',hint:'12 digits'}, {name:'pan',label:'PAN',value:ids?.pan,pattern:'[A-Za-z]{5}[0-9]{4}[A-Za-z]',hint:'AAAAA9999A'}, {name:'esiNumber',label:'ESI number',value:ids?.esi_number,pattern:'[0-9]{10}|[0-9]{17}',hint:'10 or 17 digits'}, {name:'pfMemberId',label:'PF member ID',value:ids?.pf_member_id,hint:'Establishment-linked member ID'}].map(field => <label key={field.name}>{field.label}<input name={field.name} defaultValue={field.value ?? ''} pattern={field.pattern} readOnly={!canWrite} placeholder={field.hint} /><small>{field.hint}</small></label>)}{canWrite && <Button disabled={busy}>Save identifiers</Button>}</form>{error && <p role="alert" className="form-error">{error}</p>}{notice && <p role="status" className="success-note">{notice}</p>}
  </Card>
}

type Settlement = { gratuity: { eligible: boolean; yearsCounted: number; amountPaise: number; computedPaise: number; note: string }; encashment: { days: number; amountPaise: number; byType: { leaveTypeCode: string; days: number; amountPaise: number }[] }; notice: { servedDays: number; shortfallDays: number; amountPaise: number }; recoveriesPaise: number; adhoc: { code: string; amountPaise: number; taxable?: boolean; type?: string }[] }
type Separation = { id: string; reason: string; last_working_day: string; status: 'initiated'|'in_payroll'|'settled'|'cancelled'; settlement: Settlement | null; settlement_run_id: string | null }
export function ExitPanel({ employee, data, onChanged }: { employee: Employee; data: Workspace; onChanged: () => void }) {
  const [separation, setSeparation] = useState<Separation | null>(null); const [preview, setPreview] = useState<{settlement: Settlement; final: boolean; runId?: string} | null>(null)
  const [starting, setStarting] = useState(false); const [cancelling, setCancelling] = useState(false); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const canWrite = data.permissions.includes('employee.write')
  const load = useCallback(async () => { const result = await domainApi<{separation: Separation | null}>(`/employees/${employee.id}/separation`); setSeparation(result.separation); setPreview(null) }, [employee.id])
  useEffect(() => { void load().catch(caught => setError(caught.message)) }, [load])
  const initiate = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); setError('')
    try { await domainApi(`/employees/${employee.id}/separation`, { ...values, noticeDaysRequired:Number(values.noticeDaysRequired || 0), noticeWaived:values.noticeWaived === 'on', recoveriesPaise:Math.round(Number(values.recoveries || 0)*100), recoveries:undefined }); setStarting(false); await load(); onChanged() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to start exit') } finally { setBusy(false) }
  }
  const cancel = async () => { setBusy(true); setError(''); try { await domainApi(`/separations/${separation?.id}/cancel`, {reason}); setCancelling(false); await load(); onChanged() } catch(caught) { setError(caught instanceof Error ? caught.message : 'Unable to cancel exit') } finally { setBusy(false) } }
  const stages = ['initiated','in_payroll','settled']; const current = stages.indexOf(separation?.status ?? '')
  return <Card title="Exit and final settlement" subtitle="Freezing and locking the final run is the settlement; there is no separate settlement action.">
    {separation ? <><ol className="declaration-stepper" aria-label={`Exit status: ${separation.status}`}>{stages.map((stage,index) => <li key={stage} className={index === current ? 'current' : index < current ? 'complete' : ''} aria-current={index===current?'step':undefined}><span>{index+1}</span>{pretty(stage)}</li>)}{separation.status==='cancelled' && <li className="rejected">Cancelled</li>}</ol><p>{pretty(separation.reason)} · Last working day {dateLabel(separation.last_working_day)}</p><p className="freeze-note">In payroll: the final run is frozen and figures are fixed. Settled: that run is locked and the employee has exited.</p>{canWrite && separation.status==='initiated' && <Button variant="secondary" onClick={()=>setCancelling(true)}>Cancel exit</Button>}{data.permissions.includes('payroll.process') && separation.status !== 'cancelled' && <Button variant="secondary" onClick={()=>{void domainApi<{settlement:Settlement;final:boolean;runId?:string}>(`/separations/${separation.id}/settlement-preview`).then(setPreview).catch(caught=>setError(caught.message))}}>View settlement {separation.settlement?'figures':'preview'}</Button>}</> : <p>No separation recorded.</p>}
    {canWrite && employee.status !== 'exited' && (!separation || separation.status==='cancelled') && <Button onClick={()=>setStarting(true)}>Start exit</Button>}
    {preview && <section className="settlement-report"><h3>{preview.final ? separation?.status==='settled' ? 'Final settlement — locked and paid' : 'Final settlement — fixed at freeze, awaiting lock' : 'Live settlement estimate — balances may change'}</h3>{preview.runId && <a href={`#/payroll/${preview.runId}`}>View final payroll run</a>}<dl className="details"><div><dt>Gratuity · {preview.settlement.gratuity.yearsCounted} years</dt><dd>{money(String(preview.settlement.gratuity.amountPaise))}</dd></div><div><dt>Leave encashment · {preview.settlement.encashment.days} days</dt><dd>{money(String(preview.settlement.encashment.amountPaise))}</dd></div><div><dt>Notice · {preview.settlement.notice.servedDays} served / {preview.settlement.notice.shortfallDays} shortfall days</dt><dd>{money(String(preview.settlement.notice.amountPaise))}</dd></div><div><dt>Other recoveries</dt><dd>{money(String(preview.settlement.recoveriesPaise))}</dd></div></dl><p>{preview.settlement.gratuity.note}</p>{preview.settlement.encashment.byType.map((type,index)=><p key={index}>{type.leaveTypeCode} · {type.days} days · {money(String(type.amountPaise))}</p>)}</section>}
    {starting && <Modal title="Start employee exit" onClose={()=>setStarting(false)}><form className="lifecycle-form" onSubmit={initiate}><label>Exit reason<select name="reason">{['resignation','termination','retirement','end_of_contract','death','absconding'].map(value=><option key={value} value={value}>{pretty(value)}</option>)}</select></label><label>Last working day<input required type="date" name="lastWorkingDay" min={employee.date_of_joining}/></label><label>Initiated on<input type="date" name="initiatedOn" defaultValue={data.today}/></label><label>Notice required (days)<input type="number" min="0" max="365" name="noticeDaysRequired" defaultValue="0"/></label><label><input type="checkbox" name="noticeWaived"/>Notice waived</label><label>Recoveries (₹)<input type="number" min="0" step="0.01" name="recoveries" defaultValue="0"/></label><label>Recovery note<textarea name="recoveriesNote"/></label><label>Exit note<textarea name="note"/></label><Button disabled={busy}>Record exit</Button></form></Modal>}
    {cancelling && <Modal title="Cancel exit" onClose={()=>setCancelling(false)}><label className="field">Reason for cancellation<textarea required value={reason} onChange={event=>setReason(event.target.value)}/></label><Button disabled={busy||!reason.trim()} onClick={()=>void cancel()}>Confirm cancellation</Button></Modal>}
    {error && <p role="alert" className="form-error">{error}</p>}
  </Card>
}

export function PrivacyPanel({ employee, data, onChanged }: { employee: Employee; data: Workspace; onChanged: () => void }) {
  const [eligibility,setEligibility]=useState<{ok:boolean;reason?:string}|null>(null); const [reason,setReason]=useState(''); const [review,setReview]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [counts,setCounts]=useState<Record<string,number>|null>(null)
  const canExport = data.user.employeeId===employee.id || (data.user.scope==='all' && data.permissions.includes('compensation.read'))
  const canErase = employee.status==='exited' && !employee.erased_at && data.user.scope==='all' && data.permissions.includes('employee.write')
  useEffect(()=>{if(canErase) void domainApi<{ok:boolean;reason?:string}>(`/employees/${employee.id}/erasure-eligibility`).then(setEligibility).catch(caught=>setError(caught.message))},[canErase,employee.id])
  const exportData=async()=>{setBusy(true);setError('');try{const result=await domainApi<{export:unknown}>(`/employees/${employee.id}/data-export`);downloadFile(`PEPL-${employee.employee_number}-personal-data.json`,'application/json',JSON.stringify(result.export,null,2))}catch(caught){setError(caught instanceof Error?caught.message:'Export failed')}finally{setBusy(false)}}
  const erase=async()=>{setBusy(true);setError('');try{const result=await domainApi<{anonymised:Record<string,number>}>(`/employees/${employee.id}/erase`,{reason});setCounts(result.anonymised);setReview(false);onChanged()}catch(caught){setError(caught instanceof ApiError?caught.message:'Erasure failed')}finally{setBusy(false)}}
  return <Card title="Data and privacy" subtitle="Your personal data rights and statutory retention">
    {employee.erased_at && <p className="freeze-note">Personal data erased on {dateLabel(employee.erased_at)}. The statutory payroll ledger is retained.</p>}{canExport&&<Button variant="secondary" disabled={busy} onClick={()=>void exportData()}>{data.user.employeeId===employee.id?'Download my data':'Download personal data'}</Button>}
    {canErase&&<section className="erasure-panel"><h3>Erase former employee’s personal data</h3>{!eligibility?<p>Checking statutory retention…</p>:!eligibility.ok?<p>{eligibility.reason}</p>:<><p>Eligible for erasure. This irreversibly anonymises personal data; the payroll ledger is kept.</p><label className="field">Type the reason for erasure<textarea value={reason} onChange={event=>setReason(event.target.value)} required/></label><Button variant="secondary" disabled={!reason.trim()||busy} onClick={()=>setReview(true)}>Review erasure</Button></>}</section>}
    {review&&<Modal title="Confirm irreversible erasure" onClose={()=>setReview(false)}><p>Erase personal data for {employee.first_name} {employee.last_name} ({employee.employee_number})?</p><p><strong>Reason:</strong> {reason}</p><p>This action cannot be undone. The statutory payroll ledger remains.</p><Button disabled={busy||!reason.trim()} onClick={()=>void erase()}>Erase personal data permanently</Button></Modal>}{counts&&<div role="status" className="success-note">Erasure completed.<ul>{Object.entries(counts).map(([table,count])=><li key={table}>{pretty(table)}: {count}</li>)}</ul></div>}{error&&<p role="alert" className="form-error">{error}</p>}
  </Card>
}
