import { useState,type FormEvent } from 'react'
import { ArrowRight, Check } from 'lucide-react'
import { api } from './api'
import { Button,ErrorBox,Modal } from './ui'
export interface Field {name:string;label:string;type?:string;value?:string;required?:boolean;options?:{value:string;label:string}[];help?:string;min?:string;max?:string}
export interface FormSpec {title:string;description?:string;path:string;fields:Field[];submit?:string;transform?:(values:Record<string,string>)=>unknown;success?:string}
export function ActionForm({spec,onClose,onSuccess}:{spec:FormSpec;onClose:()=>void;onSuccess:(message:string)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;const result=await api<{applied?:boolean;deferredToPeriodId?:string}>(spec.path,spec.transform?spec.transform(values):values);await onSuccess(result.deferredToPeriodId?'Correction recorded for the next open period.':spec.success??'Changes saved.');onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal title={spec.title} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit}>{spec.description&&<p className="form-intro">{spec.description}</p>}<div className="form-grid">{spec.fields.map(f=><label key={f.name} className={`field ${f.type==='textarea'?'full':''}`}><span>{f.label}{f.required!==false&&<i> *</i>}</span>{f.options?<select name={f.name} defaultValue={f.value??''} required={f.required!==false}><option value="" disabled>Select {f.label.toLowerCase()}</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value} required={f.required!==false} maxLength={2000} rows={3}/>:<input name={f.name} type={f.type??'text'} defaultValue={f.value} required={f.required!==false} min={f.min} max={f.max} maxLength={f.type==='password'?1024:200}/>} {f.help&&<small>{f.help}</small>}</label>)}</div>{error&&<ErrorBox message={error}/>}<footer className="modal-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy} type="submit">{busy?'Saving…':spec.submit??'Save changes'}<Check size={17}/></Button></footer></form></Modal>
}
export function Login({onSuccess}:{onSuccess:()=>Promise<void>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await api('/auth/login',b);await onSuccess()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="login-layout"><section className="login-art"><span className="eyebrow">A little more human.</span><h1>Great work<br/>starts with<br/><em>your people.</em></h1><div className="orbital-art" aria-hidden="true"><span/><span/><span/><div>p.</div></div><p>One thoughtful space for the everyday<br/>and everything your team becomes.</p><span className="login-footer">PEPL · People, at the heart.</span></section><section className="login-form"><div className="login-heading"><span className="eyebrow">Welcome to your workspace</span><h2>Good to have you here.</h2><p>Sign in to take care of what matters.</p></div><form onSubmit={submit}><label className="field"><span>Work email</span><input name="email" type="email" placeholder="you@company.com" autoComplete="username" required/></label><label className="field"><span>Password</span><input name="password" type="password" placeholder="Enter your password" autoComplete="current-password" required/></label>{error&&<ErrorBox message={error}/>}<Button type="submit" disabled={busy}>{busy?'Signing in…':'Enter your workspace'}<ArrowRight size={19}/></Button><p className="login-help">Need access? Your company administrator can set up your account.</p></form><div className="login-note"><span className="status-dot"/> Your company. Your people. One secure space.</div></section></div>
}
