import { useCallback, useEffect, useState } from 'react'
import { Crosshair, LocateFixed, MapPin, Pencil, Plus, RefreshCw, RotateCcw } from 'lucide-react'
import { domainApi } from './domainApi'
import type { Workspace } from './types'
import { Badge, Button, Card, Empty, ErrorBox, Skeleton } from './ui'

type Site = { id: string; code: string; name: string; lat: number; lng: number; radius_m: number; applies_to_all: boolean; location_code: string | null; status: 'active' | 'retired' }
type SiteDraft = { code: string; name: string; lat: string; lng: string; radiusM: number; appliesToAll: boolean; locationCode: string }
const empty: SiteDraft = { code: '', name: '', lat: '17.4435', lng: '78.3772', radiusM: 150, appliesToAll: true, locationCode: '' }

export function GeofenceSites() {
  const [sites, setSites] = useState<Site[]>([])
  const [draft, setDraft] = useState<SiteDraft>(empty)
  const [editing, setEditing] = useState<Site | null>(null)
  const [editorOpen, setEditorOpen] = useState(false)
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); try { setSites((await domainApi<{ sites: Site[] }>('/geofences?includeRetired=true')).sites) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load sites') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const begin = (site?: Site) => { setEditing(site ?? null); setDraft(site ? { code: site.code, name: site.name, lat: String(site.lat), lng: String(site.lng), radiusM: site.radius_m, appliesToAll: site.applies_to_all, locationCode: site.location_code ?? '' } : { ...empty }); setEditorOpen(true); setError('') }
  const currentLocation = () => navigator.geolocation?.getCurrentPosition(position => setDraft(value => ({ ...value, lat: position.coords.latitude.toFixed(6), lng: position.coords.longitude.toFixed(6) })), () => setError('Allow location access to place the pin at your current position.'), { enableHighAccuracy: true })
  const save = async () => {
    setBusy(true); setError('')
    try {
      const body = { name: draft.name, lat: Number(draft.lat), lng: Number(draft.lng), radiusM: draft.radiusM, appliesToAll: draft.appliesToAll, locationCode: draft.locationCode || null, ...(!editing ? { code: draft.code } : {}) }
      await domainApi(editing ? `/geofences/${editing.id}` : '/geofences', body, editing ? 'PATCH' : 'POST')
      setEditing(null); setEditorOpen(false); setDraft({ ...empty }); await load()
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save site') } finally { setBusy(false) }
  }
  const toggle = async (site: Site) => { setBusy(true); try { await domainApi(`/geofences/${site.id}/${site.status === 'active' ? 'retire' : 'reinstate'}`, {}); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update site') } finally { setBusy(false) } }
  const mapUrl = `https://www.openstreetmap.org/export/embed.html?bbox=${Number(draft.lng) - .012}%2C${Number(draft.lat) - .008}%2C${Number(draft.lng) + .012}%2C${Number(draft.lat) + .008}&layer=mapnik&marker=${draft.lat}%2C${draft.lng}`
  return <div className="sites-workspace">
    <div className="sites-heading"><div><span className="eyebrow">Attendance · Sites</span><h2>Where your team can punch</h2><p>Set the pin and allowed radius. Retiring a site preserves its history.</p></div><div><a className="btn secondary" href="#/settings">Attendance policy</a><Button onClick={() => begin()}><Plus size={16} />Add site</Button></div></div>
    {error && <ErrorBox message={error} />}
    {loading ? <Skeleton /> : <Card className="sites-table"><div className="table-scroll"><table><thead><tr><th>Site</th><th>Radius</th><th>Applies to</th><th>Location</th><th>Status</th><th /></tr></thead><tbody>{sites.map(site => <tr key={site.id}><td><span className="site-name"><MapPin size={17} /><span><strong>{site.name}</strong><small>{site.code}</small></span></span></td><td>{site.radius_m} m</td><td>{site.applies_to_all ? 'Everyone' : 'Assigned members'}</td><td>{site.location_code || `${site.lat.toFixed(4)}, ${site.lng.toFixed(4)}`}</td><td><Badge>{site.status}</Badge></td><td><Button variant="ghost" disabled={busy || site.status === 'retired'} onClick={() => begin(site)}><Pencil size={14} />Edit</Button><Button variant="ghost" disabled={busy} onClick={() => void toggle(site)}>{site.status === 'active' ? <RefreshCw size={14} /> : <RotateCcw size={14} />}{site.status === 'active' ? 'Retire' : 'Reinstate'}</Button></td></tr>)}</tbody></table></div>{!sites.length && <Empty title="No attendance sites" text="Add the first office, branch, or work site." />}</Card>}
    {editorOpen && <div className="mail-modal-backdrop"><section className="mail-modal site-editor" role="dialog" aria-modal="true" aria-labelledby="site-editor-title"><header><div><span>GEOFENCE</span><h2 id="site-editor-title">{editing ? `Edit ${editing.name}` : 'Add attendance site'}</h2></div><button className="mail-icon-button" onClick={() => { setEditing(null); setEditorOpen(false) }} aria-label="Close">×</button></header><div className="site-editor-grid"><div className="site-fields">{!editing && <label>Code<input required value={draft.code} onChange={event => setDraft(value => ({ ...value, code: event.target.value.toUpperCase() }))} placeholder="HQ" /></label>}<label>Name<input required value={draft.name} onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} placeholder="Head office" /></label><div className="field-pair"><label>Latitude<input type="number" step="any" value={draft.lat} onChange={event => setDraft(value => ({ ...value, lat: event.target.value }))} /></label><label>Longitude<input type="number" step="any" value={draft.lng} onChange={event => setDraft(value => ({ ...value, lng: event.target.value }))} /></label></div><Button variant="secondary" onClick={currentLocation}><LocateFixed size={15} />Use my location</Button><label>Location code<input value={draft.locationCode} onChange={event => setDraft(value => ({ ...value, locationCode: event.target.value }))} placeholder="HYD" /></label><label className="site-radius">Allowed radius <strong>{draft.radiusM} m</strong><input type="range" min="25" max="1000" step="25" value={draft.radiusM} onChange={event => setDraft(value => ({ ...value, radiusM: Number(event.target.value) }))} /></label><label className="checkbox-line"><input type="checkbox" checked={draft.appliesToAll} onChange={event => setDraft(value => ({ ...value, appliesToAll: event.target.checked }))} />Apply this site to everyone</label></div><div className="site-map"><iframe title="OpenStreetMap site preview" src={mapUrl} /><span className="site-map-pin"><Crosshair size={30} /></span><small>OpenStreetMap · move the pin with latitude and longitude</small></div></div><footer><Button variant="secondary" onClick={() => { setEditing(null); setEditorOpen(false) }}>Cancel</Button><Button disabled={busy || !draft.name || (!editing && !draft.code)} onClick={() => void save()}>{busy ? 'Saving…' : 'Save site'}</Button></footer></section></div>}
  </div>
}

export function EmployeeSites({ id, data }: { id: string; data: Workspace }) {
  const [sites, setSites] = useState<Site[]>([]); const [selected, setSelected] = useState<string[]>([]); const [exempt, setExempt] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([domainApi<{ sites: Site[] }>('/geofences'), domainApi<{ membership: { siteIds: string[]; exempt: boolean } }>(`/employees/${id}/geofences`)]).then(([all, own]) => { setSites(all.sites); setSelected(own.membership.siteIds); setExempt(own.membership.exempt) }).catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to load sites')) }, [id])
  const canEdit = data.permissions.includes('attendance.correct')
  const save = async () => { setBusy(true); try { await domainApi(`/employees/${id}/geofences`, { siteIds: exempt ? [] : selected, exempt }, 'PATCH') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update sites') } finally { setBusy(false) } }
  return <Card title="Attendance sites" subtitle="Sites where this employee may punch"><div className="site-chips">{sites.filter(site => site.applies_to_all || selected.includes(site.id)).map(site => <span key={site.id}><MapPin size={13} />{site.name}{site.applies_to_all ? ' · company-wide' : ''}</span>)}{exempt && <span>Field staff · location exempt</span>}{!exempt && !sites.some(site => site.applies_to_all || selected.includes(site.id)) && <small>No site assigned</small>}</div>{canEdit && <div className="site-membership"><label className="checkbox-line"><input type="checkbox" checked={exempt} onChange={event => setExempt(event.target.checked)} />Exempt from site restrictions</label>{!exempt && sites.filter(site => !site.applies_to_all).map(site => <label className="checkbox-line" key={site.id}><input type="checkbox" checked={selected.includes(site.id)} onChange={event => setSelected(current => event.target.checked ? [...current, site.id] : current.filter(value => value !== site.id))} />{site.name}</label>)}<Button disabled={busy} onClick={() => void save()}>Save site access</Button></div>}{error && <p className="form-error" role="alert">{error}</p>}</Card>
}
