import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Award, BarChart3, Check, ClipboardCheck, Flag, Plus, Star, Target, Users } from 'lucide-react'
import { dateLabel, fullName, pretty } from './api'
import { domainApi } from './domainApi'
import type { Workspace } from './types'
import { Avatar, Badge, Button, Card, Empty, ErrorBox, Modal, PageHeader, Skeleton, Tabs } from './ui'

type Cycle = { id: string; name: string; period_start: string; period_end: string; self_review_due: string | null; manager_review_due: string | null; rating_scale: number; status: 'draft' | 'open' | 'calibration' | 'closed' }
type Goal = { id: string; employee_id: string; cycle_id: string | null; title: string; description: string | null; kpi: string | null; target: string | null; weight_pct: number; due_on: string | null; status: string; progress_pct: number }
type Appraisal = { id: string; cycle_id: string; employee_id: string; reviewer_employee_id: string | null; status: string; self_rating: number | null; self_comments: string | null; manager_rating: number | null; manager_comments: string | null; final_rating: number | null; calibration_note: string | null; acknowledged_at: string | null }
type Pip = { id: string; employee_id: string; reason: string; objectives: Array<{ title: string; measure?: string; dueOn?: string }>; starts_on: string; review_on: string; ends_on: string; status: string; reviews: Array<{ on: string; note: string; verdict: string }> }
type Distribution = { total: number; pending: number; byRating: Record<string, number>; byDepartment: Array<{ department: string; avg: number; n: number }> }
type Dialog = { kind: 'goal' | 'checkin' | 'self' | 'review' | 'cycle' | 'calibrate' | 'pip' | 'pip-review'; item?: Goal | Appraisal | Pip }

const employeeFor = (data: Workspace, id: string) => data.employees.find(employee => employee.id === id)
const employeeLabel = (data: Workspace, id: string) => { const employee = employeeFor(data, id); return employee ? fullName(employee) : 'Employee' }

export function PerformancePage({ data }: { data: Workspace }) {
  const canReview = data.permissions.includes('performance.review'); const canManage = data.permissions.includes('performance.manage')
  const tabs = !data.user.employeeId && canManage ? ['Cycles & calibration', ...(canReview ? ['Team'] : [])] : [...(data.user.employeeId ? ['My performance'] : []), ...(canReview ? ['Team'] : []), ...(canManage ? ['Cycles & calibration'] : [])]
  const [tab, setTab] = useState(tabs[0]); const [cycles, setCycles] = useState<Cycle[]>([]); const [goals, setGoals] = useState<Goal[]>([]); const [appraisals, setAppraisals] = useState<Appraisal[]>([]); const [toReview, setToReview] = useState<Appraisal[]>([]); const [pips, setPips] = useState<Pip[]>([]); const [distribution, setDistribution] = useState<Distribution | null>(null); const [selectedCycle, setSelectedCycle] = useState(''); const [dialog, setDialog] = useState<Dialog | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const own = data.user.employeeId ? `?employeeId=${data.user.employeeId}` : ''; const [cycleResult, goalResult, appraisalResult, pipResult, reviews] = await Promise.all([domainApi<{ cycles: Cycle[] }>('/performance/cycles'), domainApi<{ goals: Goal[] }>(`/performance/goals${tab === 'My performance' ? own : ''}`), domainApi<{ appraisals: Appraisal[] }>(tab === 'My performance' ? '/performance/appraisals?mine=true' : `/performance/appraisals${selectedCycle ? `?cycleId=${selectedCycle}` : ''}`), domainApi<{ pips: Pip[] }>(`/performance/pips${tab === 'My performance' && data.user.employeeId ? `?employeeId=${data.user.employeeId}` : ''}`), canReview ? domainApi<{ appraisals: Appraisal[] }>('/performance/appraisals?toReview=true&status=manager_pending') : Promise.resolve({ appraisals: [] })]); setCycles(cycleResult.cycles); setGoals(goalResult.goals); setAppraisals(appraisalResult.appraisals); setPips(pipResult.pips); setToReview(reviews.appraisals); setSelectedCycle(current => current || cycleResult.cycles[0]?.id || '') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load performance') } finally { setLoading(false) } }, [canReview, data.user.employeeId, selectedCycle, tab])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (tab !== 'Cycles & calibration' || !selectedCycle) { setDistribution(null); return } void domainApi<Distribution>(`/performance/cycles/${selectedCycle}/distribution`).then(setDistribution).catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to load distribution')) }, [selectedCycle, tab])
  const cycle = cycles.find(item => item.id === selectedCycle)
  const mutate = async (path: string, body: unknown, message: string) => { setBusy(true); setError(''); try { await domainApi(path, body); setDialog(null); setNotice(message); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save performance update') } finally { setBusy(false) } }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!dialog) return; const v = new FormData(event.currentTarget); const item = dialog.item; if (dialog.kind === 'goal') await mutate('/performance/goals', { employeeId: tab === 'Team' ? v.get('employeeId') : undefined, cycleId: v.get('cycleId') || null, title: v.get('title'), description: v.get('description') || null, kpi: v.get('kpi') || null, target: v.get('target') || null, weightPct: Number(v.get('weight') || 0), dueOn: v.get('dueOn') || null }, 'Goal added.'); else if (dialog.kind === 'checkin') await mutate(`/performance/goals/${item!.id}/checkin`, { progressPct: Number(v.get('progress')), note: v.get('note') }, 'Check-in recorded.'); else if (dialog.kind === 'self') await mutate(`/performance/appraisals/${item!.id}/self`, { rating: Number(v.get('rating')), comments: v.get('comments') }, 'Self review submitted.'); else if (dialog.kind === 'review') await mutate(`/performance/appraisals/${item!.id}/review`, { rating: Number(v.get('rating')), comments: v.get('comments') }, 'Manager review submitted.'); else if (dialog.kind === 'cycle') await mutate('/performance/cycles', { name: v.get('name'), periodStart: v.get('periodStart'), periodEnd: v.get('periodEnd'), selfReviewDue: v.get('selfReviewDue') || null, managerReviewDue: v.get('managerReviewDue') || null, ratingScale: Number(v.get('ratingScale') || 5) }, 'Review cycle created.'); else if (dialog.kind === 'calibrate') await mutate(`/performance/appraisals/${item!.id}/calibrate`, { finalRating: Number(v.get('rating')), note: v.get('note') || undefined }, 'Rating released.'); else if (dialog.kind === 'pip') await mutate('/performance/pips', { employeeId: v.get('employeeId'), reason: v.get('reason'), objectives: [{ title: v.get('objective'), measure: v.get('measure') || undefined, dueOn: v.get('endsOn') }], startsOn: v.get('startsOn'), reviewOn: v.get('reviewOn'), endsOn: v.get('endsOn') }, 'Improvement plan opened.'); else if (dialog.kind === 'pip-review') await mutate(`/performance/pips/${item!.id}/review`, { verdict: v.get('verdict'), note: v.get('note'), extendTo: v.get('extendTo') || undefined, nextReviewOn: v.get('nextReviewOn') || undefined }, 'PIP review saved.') }
  const cycleAction = async (item: Cycle) => { if (item.status === 'draft') await mutate(`/performance/cycles/${item.id}/open`, {}, 'Cycle opened.'); else if (item.status === 'open') await mutate(`/performance/cycles/${item.id}/status`, { status: 'calibration' }, 'Cycle moved to calibration.'); else if (item.status === 'calibration') await mutate(`/performance/cycles/${item.id}/status`, { status: 'closed' }, 'Cycle closed.') }
  const acknowledge = (item: Appraisal) => mutate(`/performance/appraisals/${item.id}/acknowledge`, {}, 'Appraisal acknowledged.')
  if (loading && !cycles.length) return <Skeleton />
  return <><PageHeader title={tab === 'My performance' ? 'My performance' : tab} description="Goals, conversations and growth in one clear rhythm." eyebrow="Performance & growth">{tab === 'My performance' && <Button onClick={() => setDialog({ kind: 'goal' })}><Plus size={16} />Add goal</Button>}{tab === 'Team' && <><Button variant="secondary" onClick={() => setDialog({ kind: 'pip' })}><Flag size={16} />Open PIP</Button><Button onClick={() => setDialog({ kind: 'goal' })}><Plus size={16} />Set team goal</Button></>}{tab === 'Cycles & calibration' && <Button onClick={() => setDialog({ kind: 'cycle' })}><Plus size={16} />New cycle</Button>}</PageHeader>{error && <ErrorBox message={error} />}{notice && <p className="success-note" role="status">{notice}</p>}<Tabs value={tab} onChange={setTab} items={tabs} />
    {tab === 'My performance' ? <MyPerformance data={data} cycles={cycles} goals={goals} appraisals={appraisals} pips={pips} open={setDialog} acknowledge={acknowledge} busy={busy} /> : tab === 'Team' ? <TeamPerformance data={data} cycles={cycles} goals={goals} reviews={toReview} pips={pips} open={setDialog} /> : <Cycles data={data} cycles={cycles} selected={selectedCycle} setSelected={setSelectedCycle} cycle={cycle} appraisals={appraisals} distribution={distribution} open={setDialog} action={cycleAction} busy={busy} />}
    {dialog && <Modal title={dialogTitle(dialog, tab)} onClose={() => setDialog(null)} wide={['review', 'calibrate', 'pip'].includes(dialog.kind)}><form className="feature-form" onSubmit={submit}>{dialogFields(dialog, tab, data, cycles, cycle)}<footer><Button variant="secondary" type="button" onClick={() => setDialog(null)}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : dialogSubmit(dialog)}</Button></footer></form></Modal>}
  </>
}

function GoalCard({ goal, cycle, open }: { goal: Goal; cycle?: Cycle; open: (dialog: Dialog) => void }) { return <article className="goal-card"><header><span><Target size={17} /></span><Badge>{goal.status}</Badge></header><h3>{goal.title}</h3>{goal.description && <p>{goal.description}</p>}<div className="goal-meta"><b>{goal.weight_pct}% weight</b><span>{goal.due_on ? `Due ${dateLabel(goal.due_on)}` : cycle?.name || 'Open goal'}</span></div><div className="goal-progress"><i style={{ width: `${goal.progress_pct}%` }} /><span>{goal.progress_pct}%</span></div>{goal.status === 'active' && <Button variant="secondary" onClick={() => open({ kind: 'checkin', item: goal })}>Check in</Button>}</article> }

function MyPerformance({ data, cycles, goals, appraisals, pips, open, acknowledge, busy }: { data: Workspace; cycles: Cycle[]; goals: Goal[]; appraisals: Appraisal[]; pips: Pip[]; open: (d: Dialog) => void; acknowledge: (a: Appraisal) => void; busy: boolean }) {
  return <div className="performance-stack"><section><h2 className="section-title">Goals <span>{goals.reduce((sum, goal) => sum + (goal.status === 'active' ? goal.weight_pct : 0), 0)}% active weight</span></h2>{goals.length ? <div className="goal-grid">{goals.map(goal => <GoalCard key={goal.id} goal={goal} cycle={cycles.find(cycle => cycle.id === goal.cycle_id)} open={open} />)}</div> : <Card><Empty title="No goals yet" text="Add a measurable goal and check in as work moves." /></Card>}</section><section><h2 className="section-title">My appraisals</h2>{appraisals.length ? <div className="appraisal-grid">{appraisals.map(appraisal => <AppraisalCard key={appraisal.id} appraisal={appraisal} cycle={cycles.find(item => item.id === appraisal.cycle_id)} own open={open} acknowledge={() => void acknowledge(appraisal)} busy={busy} />)}</div> : <Card><Empty title="No appraisal is open" text="Your next review appears when HR opens a cycle." /></Card>}</section>{pips.length > 0 && <section><h2 className="section-title">Improvement plan</h2>{pips.map(pip => <PipCard key={pip.id} pip={pip} name={data.user.full_name} />)}</section>}</div>
}

function TeamPerformance({ data, cycles, goals, reviews, pips, open }: { data: Workspace; cycles: Cycle[]; goals: Goal[]; reviews: Appraisal[]; pips: Pip[]; open: (d: Dialog) => void }) {
  const byEmployee = [...new Set(goals.map(goal => goal.employee_id))]
  return <div className="performance-stack"><Card title="To review" subtitle="Self review and manager response side by side">{reviews.length ? <div className="review-queue">{reviews.map(review => <article key={review.id}><Avatar name={employeeLabel(data, review.employee_id)} /><div><strong>{employeeLabel(data, review.employee_id)}</strong><small>{cycles.find(cycle => cycle.id === review.cycle_id)?.name}</small><p>{review.self_comments || 'Self review has not been submitted; you may still review.'}</p></div><aside>{review.self_rating && <b>Self {review.self_rating}</b>}<Button onClick={() => open({ kind: 'review', item: review })}>Review</Button></aside></article>)}</div> : <Empty title="Review queue is clear" text="Appraisals waiting for you will appear here." />}</Card><section><h2 className="section-title">Team goals</h2>{byEmployee.length ? <div className="team-goals">{byEmployee.map(id => <Card key={id} title={employeeLabel(data, id)}>{goals.filter(goal => goal.employee_id === id).map(goal => <GoalCard key={goal.id} goal={goal} cycle={cycles.find(cycle => cycle.id === goal.cycle_id)} open={open} />)}</Card>)}</div> : <Card><Empty title="No team goals" text="Set the first goal for a team member." /></Card>}</section><section><h2 className="section-title">Performance improvement plans</h2>{pips.length ? pips.map(pip => <PipCard key={pip.id} pip={pip} name={employeeLabel(data, pip.employee_id)} action={<Button onClick={() => open({ kind: 'pip-review', item: pip })}>Review plan</Button>} />) : <Card><Empty title="No active plans" text="Plans are private to the employee, manager and HR." /></Card>}</section></div>
}

function Cycles({ data, cycles, selected, setSelected, cycle, appraisals, distribution, open, action, busy }: { data: Workspace; cycles: Cycle[]; selected: string; setSelected: (id: string) => void; cycle?: Cycle; appraisals: Appraisal[]; distribution: Distribution | null; open: (d: Dialog) => void; action: (c: Cycle) => void; busy: boolean }) {
  const max = Math.max(1, ...Object.values(distribution?.byRating ?? {}))
  return <div className="performance-stack"><div className="cycle-toolbar"><label>Review cycle<select value={selected} onChange={event => setSelected(event.target.value)}>{cycles.map(item => <option value={item.id} key={item.id}>{item.name} · {pretty(item.status)}</option>)}</select></label>{cycle && cycle.status !== 'closed' && <Button disabled={busy} onClick={() => void action(cycle)}>{cycle.status === 'draft' ? 'Open cycle' : cycle.status === 'open' ? 'Move to calibration' : 'Close cycle'}</Button>}</div>{cycle ? <Card className="cycle-stepper"><div className="feature-stepper">{['draft', 'open', 'calibration', 'closed'].map((step, index) => { const current = ['draft', 'open', 'calibration', 'closed'].indexOf(cycle.status); return <span className={index < current ? 'complete' : index === current ? 'current' : ''} key={step}><i>{index < current ? <Check size={14} /> : index + 1}</i><b>{pretty(step)}</b></span> })}</div></Card> : <Card><Empty title="No review cycles" text="Create a cycle to open appraisals." /></Card>}{cycle && <><Card title="Calibration table" subtitle="A note is required when HR changes the manager rating">{appraisals.length ? <div className="table-scroll"><table><thead><tr><th>Employee</th><th>Department</th><th>Self</th><th>Manager</th><th>Final</th><th /></tr></thead><tbody>{appraisals.map(appraisal => { const employee = employeeFor(data, appraisal.employee_id); return <tr key={appraisal.id}><td>{employee ? fullName(employee) : 'Employee'}</td><td>{employee?.department || '—'}</td><td>{appraisal.self_rating ?? '—'}</td><td>{appraisal.manager_rating ?? '—'}</td><td>{appraisal.final_rating ?? 'Pending'}</td><td><Button variant="ghost" disabled={appraisal.status !== 'calibration'} onClick={() => open({ kind: 'calibrate', item: appraisal })}>Calibrate</Button></td></tr>})}</tbody></table></div> : <Empty title="No appraisals" text="Opening the cycle creates an appraisal for every active employee." />}</Card>{distribution && <div className="distribution-grid"><Card title="Rating distribution" subtitle={`${distribution.pending} pending of ${distribution.total}`}><div className="rating-bars">{Array.from({ length: cycle.rating_scale }, (_, index) => String(index + 1)).map(rating => <div key={rating}><b>{rating}</b><span><i style={{ width: `${((distribution.byRating[rating] ?? 0) / max) * 100}%` }} /></span><strong>{distribution.byRating[rating] ?? 0}</strong></div>)}</div></Card><Card title="Department averages">{distribution.byDepartment.length ? <div className="department-ratings">{distribution.byDepartment.map(item => <article key={item.department}><span>{item.department}</span><b>{item.avg}</b><small>{item.n} people</small></article>)}</div> : <Empty title="No final ratings" text="Averages appear after calibration." />}</Card></div>}</>}</div>
}

function AppraisalCard({ appraisal, cycle, own, open, acknowledge, busy }: { appraisal: Appraisal; cycle?: Cycle; own?: boolean; open: (d: Dialog) => void; acknowledge: () => void; busy: boolean }) {
  const waiting = appraisal.status === 'manager_pending' ? 'With your manager' : appraisal.status === 'calibration' ? 'In calibration' : null
  return <Card className="appraisal-card"><header><div><Award size={21} /><span><strong>{cycle?.name || 'Review cycle'}</strong><small>{cycle ? `${dateLabel(cycle.period_start)} – ${dateLabel(cycle.period_end)}` : ''}</small></span></div><Badge>{appraisal.status}</Badge></header>{appraisal.status === 'self_pending' && own ? <><p>Reflect on outcomes, impact and where you want to grow.</p><Button onClick={() => open({ kind: 'self', item: appraisal })}>Write self review</Button></> : waiting ? <div className="awaiting-release"><ClockIcon /><strong>{waiting}</strong><p>Your manager’s rating and comments are awaiting release.</p></div> : <div className="rating-compare"><div><span>Self</span><b>{appraisal.self_rating ?? '—'}</b><p>{appraisal.self_comments}</p></div><div><span>Manager</span><b>{appraisal.manager_rating ?? '—'}</b><p>{appraisal.manager_comments}</p></div><div className="final"><span>Final</span><b>{appraisal.final_rating ?? '—'}</b><p>{appraisal.calibration_note}</p></div></div>}{appraisal.status === 'acknowledgement' && own && <Button disabled={busy} onClick={acknowledge}>Acknowledge appraisal</Button>}</Card>
}
function ClockIcon() { return <ClipboardCheck size={28} /> }
function PipCard({ pip, name, action }: { pip: Pip; name: string; action?: React.ReactNode }) { return <Card className="pip-card"><header><div><Flag size={18} /><span><strong>{name}</strong><small>{dateLabel(pip.starts_on)} – {dateLabel(pip.ends_on)} · review {dateLabel(pip.review_on)}</small></span></div><Badge>{pip.status}</Badge></header><p>{pip.reason}</p><ul>{pip.objectives.map((objective, index) => <li key={`${objective.title}-${index}`}><Check size={14} /><span><strong>{objective.title}</strong>{objective.measure && <small>{objective.measure}</small>}</span></li>)}</ul>{pip.reviews.length > 0 && <div className="pip-reviews">{pip.reviews.map((review, index) => <p key={`${review.on}-${index}`}><b>{dateLabel(review.on)} · {pretty(review.verdict)}</b>{review.note}</p>)}</div>}{action}</Card> }

function dialogTitle(dialog: Dialog, tab: string) { return ({ goal: tab === 'Team' ? 'Set team goal' : 'Add goal', checkin: 'Goal check-in', self: 'Self review', review: 'Manager review', cycle: 'New review cycle', calibrate: 'Calibrate and release', pip: 'Open improvement plan', 'pip-review': 'Review improvement plan' })[dialog.kind] }
function dialogSubmit(dialog: Dialog) { return ({ goal: 'Save goal', checkin: 'Record check-in', self: 'Submit self review', review: 'Submit review', cycle: 'Create draft cycle', calibrate: 'Release rating', pip: 'Open plan', 'pip-review': 'Save review' })[dialog.kind] }
function dialogFields(dialog: Dialog, tab: string, data: Workspace, cycles: Cycle[], selectedCycle?: Cycle) {
  const item = dialog.item
  if (dialog.kind === 'goal') return <>{tab === 'Team' && <label>Employee<select name="employeeId" required defaultValue=""><option value="" disabled>Choose employee</option>{data.employees.filter(employee => employee.id !== data.user.employeeId).map(employee => <option key={employee.id} value={employee.id}>{fullName(employee)}</option>)}</select></label>}<label>Goal title<input name="title" required /></label><label>Description<textarea name="description" rows={3} /></label><div className="field-pair"><label>KPI<input name="kpi" /></label><label>Target<input name="target" /></label></div><div className="field-pair"><label>Cycle<select name="cycleId"><option value="">No cycle</option>{cycles.filter(cycle => cycle.status !== 'closed').map(cycle => <option value={cycle.id} key={cycle.id}>{cycle.name}</option>)}</select></label><label>Weight %<input name="weight" type="number" min="0" max="100" defaultValue="0" /></label></div><label>Due on<input name="dueOn" type="date" /></label></>
  if (dialog.kind === 'checkin') { const goal = item as Goal; return <><div className="dialog-context"><Target /><div><strong>{goal.title}</strong><small>Currently {goal.progress_pct}% complete</small></div></div><label>Progress <output>{goal.progress_pct}%</output><input name="progress" type="range" min="0" max="100" defaultValue={goal.progress_pct} /></label><label>What moved?<textarea name="note" required rows={3} /></label></> }
  if (dialog.kind === 'self' || dialog.kind === 'review') { const appraisal = item as Appraisal; const scale = cycles.find(cycle => cycle.id === appraisal.cycle_id)?.rating_scale ?? 5; return <>{dialog.kind === 'review' && <div className="self-review-context"><span><b>Self rating</b><strong>{appraisal.self_rating ?? 'Not submitted'}</strong></span><p>{appraisal.self_comments || 'The employee has not submitted a self review.'}</p></div>}<label>Rating<select name="rating" required defaultValue=""><option value="" disabled>Choose 1–{scale}</option>{Array.from({ length: scale }, (_, index) => index + 1).map(value => <option value={value} key={value}>{value} / {scale}</option>)}</select></label><label>Comments<textarea name="comments" required rows={6} /></label></> }
  if (dialog.kind === 'cycle') return <><label>Cycle name<input name="name" required /></label><div className="field-pair"><label>Period starts<input name="periodStart" type="date" required /></label><label>Period ends<input name="periodEnd" type="date" required /></label></div><div className="field-pair"><label>Self review due<input name="selfReviewDue" type="date" /></label><label>Manager review due<input name="managerReviewDue" type="date" /></label></div><label>Rating scale<input name="ratingScale" type="number" min="3" max="10" defaultValue="5" /></label></>
  if (dialog.kind === 'calibrate') { const appraisal = item as Appraisal; return <><div className="calibration-context"><span>Self <b>{appraisal.self_rating ?? '—'}</b></span><span>Manager <b>{appraisal.manager_rating ?? '—'}</b></span></div><label>Final rating<select name="rating" defaultValue={appraisal.manager_rating ?? ''} required>{Array.from({ length: selectedCycle?.rating_scale ?? 5 }, (_, index) => index + 1).map(value => <option key={value}>{value}</option>)}</select></label><label>Calibration note<textarea name="note" rows={4} placeholder="Required when the final rating changes" /></label></> }
  if (dialog.kind === 'pip') return <><label>Employee<select name="employeeId" required defaultValue=""><option value="" disabled>Choose employee</option>{data.employees.filter(employee => employee.id !== data.user.employeeId).map(employee => <option value={employee.id} key={employee.id}>{fullName(employee)}</option>)}</select></label><label>Reason<textarea name="reason" required rows={3} /></label><label>Objective<input name="objective" required /></label><label>Measure of success<input name="measure" /></label><div className="field-pair"><label>Starts on<input name="startsOn" type="date" required /></label><label>Review on<input name="reviewOn" type="date" required /></label></div><label>Ends on<input name="endsOn" type="date" required /></label></>
  return <><label>Verdict<select name="verdict"><option value="continue">Continue</option><option value="extend">Extend</option><option value="close_success">Close successfully</option><option value="close_exit">Close for exit</option></select></label><label>Review note<textarea name="note" required rows={4} /></label><div className="field-pair"><label>Extend to<input name="extendTo" type="date" /></label><label>Next review on<input name="nextReviewOn" type="date" /></label></div></>
}
