import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { CalendarRange, Camera, Clock3, House, MapPinned, Navigation, Plus, Square } from 'lucide-react'
import { dateLabel, fullName, pretty } from './api'
import { domainApi } from './domainApi'
import type { Workspace } from './types'
import { Badge, Button, Card, Empty, ErrorBox, Modal, Tabs } from './ui'
import { locate } from './geo'

export type RemoteRequest = { id: string; employee_id: string; kind: 'wfh' | 'field'; starts_on: string; ends_on: string; place: string | null; reason: string | null; status: string; created_at: string }
type Visit = { id: string; employee_id: string; work_date: string; place: string; contact: string | null; purpose: string; started_at: string; ended_at: string | null; outcome: string | null; next_step: string | null }
const fileBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] ?? ''); reader.onerror = reject; reader.readAsDataURL(file) })

export function RemoteWorkPanel({ data }: { data: Workspace }) {
  const [requests, setRequests] = useState<RemoteRequest[]>([]); const [visits, setVisits] = useState<Visit[]>([]); const [tab, setTab] = useState('My requests'); const [dialog, setDialog] = useState<'request' | 'start' | 'end' | null>(null); const [kind, setKind] = useState<'wfh' | 'field'>('wfh'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [now, setNow] = useState(Date.now()); const [photos, setPhotos] = useState<File[]>([])
  const managerView = data.user.scope !== 'self' && data.permissions.includes('attendance.correct')
  const load = useCallback(async () => { try { const suffix = tab === 'Team calendar' ? `?status=approved&from=${data.today.slice(0, 8)}01&to=${data.today.slice(0, 8)}31` : data.user.employeeId ? `?employeeId=${data.user.employeeId}` : ''; const [remote, field] = await Promise.all([domainApi<{ requests: RemoteRequest[] }>(`/attendance/remote-requests${suffix}`), domainApi<{ visits: Visit[] }>(`/attendance/visits${tab === 'Team calendar' ? '' : data.user.employeeId ? `?employeeId=${data.user.employeeId}` : ''}`)]); setRequests(remote.requests); setVisits(field.visits) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load remote work') } }, [data.today, data.user.employeeId, tab])
  useEffect(() => { void load() }, [load])
  const openVisit = visits.find(visit => !visit.ended_at && visit.employee_id === data.user.employeeId)
  useEffect(() => { if (!openVisit) return; const timer = window.setInterval(() => setNow(Date.now()), 30_000); return () => window.clearInterval(timer) }, [openVisit])
  const request = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setError(''); try { await domainApi('/attendance/remote-requests', { kind, startsOn: values.get('startsOn'), endsOn: values.get('endsOn'), place: kind === 'field' ? values.get('place') : undefined, reason: values.get('reason') || undefined }); setDialog(null); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to send request') } finally { setBusy(false) } }
  const cancel = async (id: string) => { setBusy(true); try { await domainApi(`/attendance/remote-requests/${id}/cancel`, {}); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to cancel request') } finally { setBusy(false) } }
  const start = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); try { const geo = await locate(); await domainApi('/attendance/visits', { place: values.get('place'), contact: values.get('contact') || undefined, purpose: values.get('purpose'), ...(geo ? { geo } : {}) }); setDialog(null); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to start visit') } finally { setBusy(false) } }
  const end = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!openVisit) return; const values = new FormData(event.currentTarget); setBusy(true); try { const geo = await locate(); const photoDocumentIds = await Promise.all(photos.map(async file => { const result = await domainApi<{ id: string }>('/documents', { ownerType: 'employee', ownerId: data.user.employeeId, fileName: file.name, contentType: file.type || 'image/jpeg', contentBase64: await fileBase64(file), category: 'other', isConfidential: true }); return result.id })); await domainApi(`/attendance/visits/${openVisit.id}/end`, { outcome: values.get('outcome'), nextStep: values.get('nextStep') || undefined, photoDocumentIds, ...(geo ? { geo } : {}) }); setPhotos([]); setDialog(null); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to end visit') } finally { setBusy(false) } }
  const calendarDays = useMemo(() => Array.from({ length: new Date(Number(data.today.slice(0, 4)), Number(data.today.slice(5, 7)), 0).getDate() }, (_, index) => `${data.today.slice(0, 8)}${String(index + 1).padStart(2, '0')}`), [data.today])
  const elapsed = openVisit ? Math.max(0, Math.floor((now - new Date(openVisit.started_at).getTime()) / 60000)) : 0
  return <section className="remote-work"><header><div><span className="eyebrow">Flexible attendance</span><h2>Work from home & field duty</h2></div><div>{data.user.employeeId && <Button variant="secondary" onClick={() => setDialog('request')}><CalendarRange size={16} />Request remote work</Button>}{data.user.employeeId && !openVisit && <Button onClick={() => setDialog('start')}><Navigation size={16} />Start visit</Button>}</div></header>{error && <ErrorBox message={error} />}{managerView && <Tabs value={tab} onChange={setTab} items={['My requests', 'Team calendar']} />}
    {openVisit && tab === 'My requests' && <Card className="live-visit"><div className="live-pulse"><i /><MapPinned size={22} /></div><div><span>VISIT IN PROGRESS</span><h3>{openVisit.place}</h3><p>{openVisit.purpose}</p></div><strong>{Math.floor(elapsed / 60)}h {String(elapsed % 60).padStart(2, '0')}m</strong><Button onClick={() => setDialog('end')}><Square size={15} />End visit</Button></Card>}
    {tab === 'Team calendar' ? <><Card className="remote-calendar" title="Approved remote calendar" subtitle={dateLabel(`${data.today.slice(0, 8)}01`, { month: 'long', year: 'numeric' })}><div className="remote-calendar-grid"><div className="calendar-corner">Team member</div>{calendarDays.map(day => <b key={day}>{Number(day.slice(-2))}</b>)}{data.employees.map(employee => <div className="remote-calendar-row" key={employee.id}><strong>{fullName(employee)}</strong>{calendarDays.map(day => { const item = requests.find(request => request.employee_id === employee.id && day >= request.starts_on && day <= request.ends_on); return <span key={day} className={item?.kind ?? ''} title={item ? `${pretty(item.kind)} · ${item.place ?? ''}` : ''}>{item ? item.kind === 'wfh' ? <House size={12} /> : <MapPinned size={12} /> : null}</span>})}</div>)}</div></Card><Card title="Team field visits" subtitle="Visit purpose, contact and outcome">{visits.length ? <div className="visit-timeline">{visits.map(visit => <article key={visit.id}><span><MapPinned size={15} /></span><div><strong>{employeeLabel(data, visit.employee_id)} · {visit.place}</strong><small>{dateLabel(visit.work_date)} · {visit.contact || 'No contact recorded'}</small><p>{visit.purpose}</p>{visit.outcome && <p><b>Outcome:</b> {visit.outcome}</p>}{visit.next_step && <p><b>Next:</b> {visit.next_step}</p>}</div><Badge>{visit.ended_at ? 'completed' : 'active'}</Badge></article>)}</div> : <Empty title="No team visits" text="Field visits from your permitted team appear here." />}</Card></>
    : <div className="remote-columns"><Card title="My requests" subtitle="Pending and approved arrangements">{requests.length ? <div className="request-list">{requests.map(item => <article key={item.id}><span className={item.kind}><House size={17} /></span><div><strong>{item.kind === 'wfh' ? 'Work from home' : 'Field duty'}</strong><small>{dateLabel(item.starts_on)}{item.ends_on !== item.starts_on ? ` – ${dateLabel(item.ends_on)}` : ''}{item.place ? ` · ${item.place}` : ''}</small></div><Badge>{item.status}</Badge>{['pending', 'approved'].includes(item.status) && <Button variant="ghost" disabled={busy} onClick={() => void cancel(item.id)}>Cancel</Button>}</article>)}</div> : <Empty title="No remote requests" text="Your WFH and field-duty requests will appear here." />}</Card><Card title="Field visit timeline" subtitle="Last 30 days">{visits.length ? <div className="visit-timeline">{visits.map(visit => <article key={visit.id}><span><MapPinned size={15} /></span><div><strong>{visit.place}</strong><small>{dateLabel(visit.work_date)} · {visit.contact || 'No contact recorded'}</small><p>{visit.purpose}</p>{visit.outcome && <p><b>Outcome:</b> {visit.outcome}</p>}{visit.next_step && <p><b>Next:</b> {visit.next_step}</p>}</div><Badge>{visit.ended_at ? 'completed' : 'active'}</Badge></article>)}</div> : <Empty title="No field visits" text="Start a visit to capture purpose, location and outcome." />}</Card></div>}
    {dialog === 'request' && <Modal title="Work from home / field duty" onClose={() => setDialog(null)}><form className="feature-form" onSubmit={request}><label>Arrangement<select value={kind} onChange={event => setKind(event.target.value as 'wfh' | 'field')}><option value="wfh">Work from home</option><option value="field">Field duty</option></select></label><div className="field-pair"><label>Starts on<input name="startsOn" type="date" defaultValue={data.today} required /></label><label>Ends on<input name="endsOn" type="date" defaultValue={data.today} required /></label></div>{kind === 'field' && <label>Place / client / site<input name="place" required /></label>}<label>Reason<textarea name="reason" rows={3} /></label><footer><Button variant="secondary" type="button" onClick={() => setDialog(null)}>Cancel</Button><Button disabled={busy}>{busy ? 'Sending…' : 'Send request'}</Button></footer></form></Modal>}
    {dialog === 'start' && <Modal title="Start field visit" onClose={() => setDialog(null)}><form className="feature-form" onSubmit={start}><label>Place<input name="place" required autoFocus /></label><label>Contact person<input name="contact" /></label><label>Purpose<textarea name="purpose" required rows={3} /></label><p className="form-hint"><Navigation size={14} />Your location is captured when available.</p><footer><Button variant="secondary" type="button" onClick={() => setDialog(null)}>Cancel</Button><Button disabled={busy}>Start visit</Button></footer></form></Modal>}
    {dialog === 'end' && openVisit && <Modal title={`End visit · ${openVisit.place}`} onClose={() => setDialog(null)}><form className="feature-form" onSubmit={end}><label>Outcome<textarea name="outcome" required rows={3} /></label><label>Next step<textarea name="nextStep" rows={2} /></label><label className="photo-upload"><Camera size={19} /><span>{photos.length ? `${photos.length} photo${photos.length === 1 ? '' : 's'} selected` : 'Add visit photos'}</span><input type="file" accept="image/*" multiple onChange={event => setPhotos(Array.from(event.target.files ?? []))} /></label><footer><Button variant="secondary" type="button" onClick={() => setDialog(null)}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'End and save visit'}</Button></footer></form></Modal>}
  </section>
}

function employeeLabel(data: Workspace, id: string) { const employee = data.employees.find(item => item.id === id); return employee ? fullName(employee) : 'Employee' }
